"""Add search_history table

Revision ID: 187d5a4fbf91
Revises: c3f9a1b2e4d7
Create Date: 2026-02-27 17:25:48.554712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187d5a4fbf91'
down_revision: Union[str, Sequence[str], None] = 'c3f9a1b2e4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('internal_results', sa.JSON(), nullable=True),
    sa.Column('external_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_index(op.f('ix_search_history_query'), 'search_history', ['query'], unique=False)
    op.create_table('project_vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_vendors_id'), 'project_vendors', ['id'], unique=False)
    op.drop_constraint(op.f('uq_vendors_name'), 'vendors', type_='unique')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_vendors_name'), 'vendors', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_project_vendors_id'), table_name='project_vendors')
    op.drop_table('project_vendors')
    op.drop_index(op.f('ix_search_history_query'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_table('search_history')
    # ### end Alembic commands ###
