"""Merge Project and RFP tables and add ProjectVendor

Revision ID: 28efc5582535
Revises: d554ef8702e6
Create Date: 2026-02-26 18:34:00.565338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28efc5582535'
down_revision: Union[str, Sequence[str], None] = 'd554ef8702e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_vendors_id'), 'project_vendors', ['id'], unique=False)
    op.drop_index(op.f('ix_rfps_id'), table_name='rfps')
    op.drop_table('rfps')
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_vendors_gstin'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_headquarters_city'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_headquarters_state'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_is_active'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_is_verified'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_vendor_type'), table_name='vendors')
    op.drop_column('vendors', 'profile_completion_score')
    op.drop_column('vendors', 'updated_at')
    op.drop_column('vendors', 'description')
    op.drop_column('vendors', 'founded_year')
    op.drop_column('vendors', 'headquarters_city')
    op.drop_column('vendors', 'gstin')
    op.drop_column('vendors', 'overall_rating')
    op.drop_column('vendors', 'cin')
    op.drop_column('vendors', 'iec_code')
    op.drop_column('vendors', 'headquarters_pincode')
    op.drop_column('vendors', 'gem_registered')
    op.drop_column('vendors', 'vendor_type')
    op.drop_column('vendors', 'msme_udyam_number')
    op.drop_column('vendors', 'contact_person_name')
    op.drop_column('vendors', 'contact_phone')
    op.drop_column('vendors', 'pan_number')
    op.drop_column('vendors', 'is_active')
    op.drop_column('vendors', 'headquarters_state')
    op.drop_column('vendors', 'headquarters_country')
    op.drop_column('vendors', 'is_verified')
    op.drop_column('vendors', 'total_ratings_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('total_ratings_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('headquarters_country', sa.VARCHAR(), server_default=sa.text("'India'::character varying"), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('headquarters_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('pan_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('contact_person_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('msme_udyam_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('vendor_type', postgresql.ENUM('manufacturer', 'trader', 'distributor', 'retailer', 'service_provider', 'consultant', 'works_contractor', name='vendortype'), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('gem_registered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('headquarters_pincode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('iec_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('cin', sa.VARCHAR(length=21), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('overall_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('gstin', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('headquarters_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('founded_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('profile_completion_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_vendors_vendor_type'), 'vendors', ['vendor_type'], unique=False)
    op.create_index(op.f('ix_vendors_is_verified'), 'vendors', ['is_verified'], unique=False)
    op.create_index(op.f('ix_vendors_is_active'), 'vendors', ['is_active'], unique=False)
    op.create_index(op.f('ix_vendors_headquarters_state'), 'vendors', ['headquarters_state'], unique=False)
    op.create_index(op.f('ix_vendors_headquarters_city'), 'vendors', ['headquarters_city'], unique=False)
    op.create_index(op.f('ix_vendors_gstin'), 'vendors', ['gstin'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table('rfps',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('rfps_project_id_fkey')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('rfps_vendor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rfps_pkey'))
    )
    op.create_index(op.f('ix_rfps_id'), 'rfps', ['id'], unique=False)
    op.drop_index(op.f('ix_project_vendors_id'), table_name='project_vendors')
    op.drop_table('project_vendors')
    # ### end Alembic commands ###
