"""Add project RFP deadline, timeline, search intent

Revision ID: 40a3e79f7305
Revises: 9d92dc8244be
Create Date: 2026-03-05 12:34:12.944013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a3e79f7305'
down_revision: Union[str, Sequence[str], None] = '9d92dc8244be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('rfp_deadline', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('delivery_timeline', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('search_intent', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'search_intent')
    op.drop_column('projects', 'delivery_timeline')
    op.drop_column('projects', 'rfp_deadline')
    # ### end Alembic commands ###
