"""add negotiated price

Revision ID: 626178472c0a
Revises: e660f3dbeda8
Create Date: 2026-03-06 04:44:21.541948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626178472c0a'
down_revision: Union[str, Sequence[str], None] = 'e660f3dbeda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('negotiated_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'negotiated_price')
    # ### end Alembic commands ###
