"""Merge Project and RFP tables and add ProjectVendor

Revision ID: 68e395a9695b
Revises: 28efc5582535
Create Date: 2026-02-26 18:44:03.557730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68e395a9695b"
down_revision: Union[str, Sequence[str], None] = "28efc5582535"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'PUBLISHED'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'IN_PROGRESS'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'COMPLETED'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'DRAFT'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'published'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'in-progress'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'completed'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'draft'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing ENUM values in Postgres is not natively supported by ALTER TYPE.
    # We would need to recreate the type if this was a strict downgrade.
    pass
    # ### end Alembic commands ###
