"""add ai_recommendations to Project

Revision ID: 797a06e88349
Revises: a1b2c3d4e5f6
Create Date: 2026-03-03 09:25:49.897845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797a06e88349'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ai_recommendations', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('uq_vendors_name'), 'vendors', type_='unique')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_vendors_name'), 'vendors', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'ai_recommendations')
    # ### end Alembic commands ###
