"""Add quote extraction fields

Revision ID: e660f3dbeda8
Revises: 40a3e79f7305
Create Date: 2026-03-05 18:00:10.540009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e660f3dbeda8'
down_revision: Union[str, Sequence[str], None] = '40a3e79f7305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('delivery_timeline', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('quality_standards', sa.Text(), nullable=True))
    op.add_column('quotes', sa.Column('warranty_terms', sa.Text(), nullable=True))
    op.add_column('quotes', sa.Column('compliance_certifications', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'compliance_certifications')
    op.drop_column('quotes', 'warranty_terms')
    op.drop_column('quotes', 'quality_standards')
    op.drop_column('quotes', 'delivery_timeline')
    # ### end Alembic commands ###
